version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
#    expose:
#      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=donasi_db
    volumes:
      - "postgres-donasi:/data/db"
    ports:
      - "5431:5432"
  donasi:
    depends_on:
      - postgres
    container_name: donasi
    build:
      context: "."
      dockerfile: Dockerfile
    image: "ahyalfan/donasi:1.0.0"
#    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=donasi_db
volumes:
  postgres-donasi:
    name: postgres-donasi